config/routes.rb
Mapper::Application.routes.draw do

    root 'places#index'
    resources :places

end

app/models/place.rb
class Place < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/places_controller.rb
class PlacesController < ApplicationController
	def index
		@place = Place.last
	end

	def new
		@place = Place.new
	end

	def create 
		@place = Place.create(place_params)
		redirect_to root_path
end
end

private

def place_params
	params.require(:place).permit(:title, :address)
	end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/places_helper.rb
module PlacesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Mapper</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<h2>
	<%= link_to 'Mapper', root_path %>
</h2>
<h2>
	<%= link_to 'New+', new_place_path %>
</h2>
<%= yield %>

</body>
</html>

app/views/places/index.html.erb
<div class="span4 offset4 text body-center">
<h1> Latest Places </h1>
<% if @place.present? %>
Title: <%= @place.title %>
<br/>
Address: <%= @place.address %>
<%else %>
	<h2> enter a place </h2>
<% end %>	
</div>

app/views/places/new.html.erb
<h1> Stuff here </h1>

<%= simple_form_for @place do |f| %>
	<%= f.input :title %>
	<%= f.input :address %>
	<%= submit_tag 'create' %>
	
	<% end %>